#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  DISTRIB=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
  if [[ ${DISTRIB} = *"Debian"* ]]; then
     wget https://swayos.github.io/setup-debian.sh
     bash setup-debian.sh
  elif [[ ${DISTRIB} = *"Void"* ]]; then
     wget https://swayos.github.io/setup-void.sh
     bash setup-void.sh
  else
     echo "$DISTRIB is not supported yet, feel free to add a $DISTRIB installer to SwayOS based on setup-arch.sh"
  fi
#elif [[ "$OSTYPE" == "freebsd"* ]]; then
#    wget https://swayos.github.io/setup-freebsd.sh
#    bash setup-freebsd.sh
else
  echo "$OSTYPE is not supported yet, feel free to add a $OSTYPE installer to SwayOS based on setup-arch.sh"
fi
