#!/bin/bash


printf "Installing needed official packages" | tee -a ~/sway_setup_log


sudo pacman -S --noconfirm --needed git zsh zsh-autosuggestions iwd bluez bluez-utils blueman pipewire pipewire-alsa pipewire-pulse pipewire-jack pipewire-media-session xdg-desktop-portal-wlr xorg-xwayland wayland-protocols sway swayidle swaylock grim slurp waybar wofi brightnessctl foot ttf-font-awesome nautilus libreoffice-fresh gnome-system-monitor system-config-printer feh cups ttf-ubuntu-font-family polkit-gnome wl-clipboard openbsd-netcat unzip meson | tee -a ~/sway_setup_log


printf "\nCloning swayOS repo" | tee -a ~/sway_setup_log

curl -LO https://github.com/swayos/swayos.github.io/archive/master.zip | tee -a ~/sway_setup_log
unzip master.zip | tee -a ~/sway_setup_log
cd swayos.github.io-main


printf "\nCopying terminus-ttf fonts to font directory" | tee -a ~/sway_setup_log

sudo cp -f font/*.* /usr/share/fonts/ echo "copying terminus-ttf to font directory" >> ~/sway_setup_log | tee -a ~/sway_setup_log


printf "\nCopying settings to home folder" | tee -a ~/sway_setup_log

cp -f -R home/. ~/ | tee -a ~/sway_setup_log


print "\nStarting services" | tee -a ~/sway_setup_log

echo $'[Match]\nName=enp1s0\n[Network]\nDHCP=yes\n' | sudo tee /etc/systemd/network/20-wired.network > /dev/null

sudo systemctl enable systemd-networkd --now | tee -a ~/sway_setup_log
sudo systemctl enable iwd --now | tee -a ~/sway_setup_log
sudo systemctl enable bluetooth --now | tee -a ~/sway_setup_log
sudo systemctl enable cups --now | tee -a ~/sway_setup_log


printf "\nInstalling yay for aur programs" | tee -a ~/sway_setup_log

git clone https://aur.archlinux.org/yay.git | tee -a ~/sway_setup_log
cd yay
makepkg -si
cd ..


printf "\nInstalling needed aur packages" | tee -a ~/sway_setup_log

yay --noconfirm -S google-chrome pamac-gtk iwgtk wdisplays wob wlogout | tee -a ~/sway_setup_log


printf "\nInstalling sway overview from the repo until it is in aur" | tee -a ~/sway_setup_log

git clone https://github.com/milgra/sway-overview.git | tee -a ~/sway_setup_log
cd sway-overview
meson build
ninja -C build
sudo ninja -C build install
cd ..

printf "\nCleaning up" | tee -a ~/sway_setup_log

cd ..
rm -f -R swayos | tee -a ~/sway_setup_log
rm -f -R master.zip | tee -a ~/sway_setup_log
rm -f -R swayos.github.io-main | tee -a ~/sway_setup_log

printf "\nChanging shell to zsh" | tee -a ~/sway_setup_log

chsh -s /bin/zsh | tee -a ~/sway_setup_log


printf "\nSetup is done, please log out and log in back again ( type exit )" | tee -a ~/sway_setup_log
