#!/bin/bash

log(){
    printf "$1" | tee -a ~/sway_setup_log    
}

check(){
    if [ "$?" != "0" ]; then
	printf "$1 error : $?" | tee -a ~/sway_setup_log
	exit 1
    fi
}

log "Listing input devices, add setup blocks in sway config for keyboard and touchpad"

# create empty pre-configured keyboard and touchpad sway config blocks

echo $'input "_id_" {\nrepeat_rate 100\nrepeat_delay 250\n}' | tee config_keyboard
echo $'input "_id_" {\ndwt enabled\ntap enabled\nnatural_scroll enabled\nmiddle_emulation enabled\n}' | tee config_touchpad

# look for keyboard and touchpad input devices, add them to configuration

swaymsg -t get_inputs | grep -i "identifier.*keyboard" | cut -d'"' -f 4 | while read -r line ; do
    log "Creating rules for keyboard $line"
    # substitute device identifier in config_keyboard
    sed "s/_id_/$line/" config_keyboard > config_temp
    check "sed"
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
    check "sed"
done

swaymsg -t get_inputs | grep -i "identifier.*touchpad" | cut -d'"' -f 4 | while read -r line ; do
    log "Creating rules for touchpad $line"
    # substitute device identifier in config_touchpad
    sed "s/_id_/$line/" config_touchpad > config_temp
    check "sed"
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
    check "sed"
done


log "Removing last two lines of sway config"
head -n -3 ~/.config/sway/config
check "head"


log "Removing setup script"
rm -f ~/.config/sway/setup
check "rm"


log "Reloading sway"
swaymsg reload
check "swaymsg reload"
