#!/bin/bash

echo "listing input devices, add setup blocks in sway config for keyboard and touchpad"

# create empty pre-configured keyboard and touchpad sway config blocks

echo "input '_id_' {\nrepeat_rate 100\nrepeat_delay 250\n}" > config_keyboard
echo "input '_id_' {\ndwt enabled\ntap enabled\nnatural_scroll enabled\nmiddle_emulation enabled\n}" > config_touchpad

# look for keyboard and touchpad input devices, add them to configuration

swaymsg -t get_inputs | grep -i "identifier.*keyboard" | cut -d'"' -f 4 | while read -r line ; do
    echo "Creating rules for keyboard $line"
    # substitute device identifier in config_keyboard
    sed "s/_id_/$line/" config_keyboard > config_temp
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
done

swaymsg -t get_inputs | grep -i "identifier.*touchpad" | cut -d'"' -f 4 | while read -r line ; do
    echo "Creating rules for touchpad $line"
    # substitute device identifier in config_touchpad
    sed "s/_id_/$line/" config_touchpad > config_temp
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
done

# remove last line of sway config

sed -i '$ d' ~/.config/sway/config

# remove this script

# rm ~/.config/sway/config
