#!/bin/bash

echo "Listing input devices, add setup blocks in sway config for keyboard and touchpad" | tee -a ~/sway_setup_log

# create empty pre-configured keyboard and touchpad sway config blocks

echo $'input "_id_" {\nrepeat_rate 100\nrepeat_delay 250\n}' | tee config_keyboard
echo $'input "_id_" {\ndwt enabled\ntap enabled\nnatural_scroll enabled\nmiddle_emulation enabled\n}' | tee config_touchpad

# look for keyboard and touchpad input devices, add them to configuration

swaymsg -t get_inputs | grep -i "identifier.*keyboard" | cut -d'"' -f 4 | while read -r line ; do
    echo "Creating rules for keyboard $line" | tee -a ~/sway_setup_log
    # substitute device identifier in config_keyboard
    sed "s/_id_/$line/" config_keyboard > config_temp
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
done

swaymsg -t get_inputs | grep -i "identifier.*touchpad" | cut -d'"' -f 4 | while read -r line ; do
    echo "Creating rules for touchpad $line" | tee -a ~/sway_setup_log
    # substitute device identifier in config_touchpad
    sed "s/_id_/$line/" config_touchpad > config_temp
    # insert resulting file into sway config
    sed -i -e '/# devices/r./config_temp' ~/.config/sway/config
done

# remove last two lines of sway config

echo "Removing last two lines of sway config" >> | tee -a ~/sway_setup_log

head -n -3 ~/.config/sway/config

# remove this script

echo "Removing setup script" | tee -a ~/sway_setup_log

rm -f ~/.config/sway/setup | tee -a ~/sway_setup_log

echo "Reloading sway" | tee -a ~/sway_setup_log

# reload sway
swaymsg reload | tee -a ~/sway_setup_log
